# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab6.proto',
  package='lab6',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlab6.proto\x12\x04lab6\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xd3\x01\n\x04Lab6\x12\'\n\x05\x44oAdd\x12\x0c.lab6.addMsg\x1a\x0e.lab6.addReply\"\x00\x12:\n\nDotProduct\x12\x13.lab6.dotProductMsg\x1a\x15.lab6.dotProductReply\"\x00\x12\x31\n\x08RawImage\x12\x11.lab6.rawImageMsg\x1a\x10.lab6.imageReply\"\x00\x12\x33\n\tJsonImage\x12\x12.lab6.jsonImageMsg\x1a\x10.lab6.imageReply\"\x00\x62\x06proto3'
)




_ADDMSG = _descriptor.Descriptor(
  name='addMsg',
  full_name='lab6.addMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='lab6.addMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='lab6.addMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_RAWIMAGEMSG = _descriptor.Descriptor(
  name='rawImageMsg',
  full_name='lab6.rawImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='lab6.rawImageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=78,
)


_DOTPRODUCTMSG = _descriptor.Descriptor(
  name='dotProductMsg',
  full_name='lab6.dotProductMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='lab6.dotProductMsg.a', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='lab6.dotProductMsg.b', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=117,
)


_JSONIMAGEMSG = _descriptor.Descriptor(
  name='jsonImageMsg',
  full_name='lab6.jsonImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='lab6.jsonImageMsg.img', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=146,
)


_ADDREPLY = _descriptor.Descriptor(
  name='addReply',
  full_name='lab6.addReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='lab6.addReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=171,
)


_DOTPRODUCTREPLY = _descriptor.Descriptor(
  name='dotProductReply',
  full_name='lab6.dotProductReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dotproduct', full_name='lab6.dotProductReply.dotproduct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=210,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='imageReply',
  full_name='lab6.imageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='lab6.imageReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='lab6.imageReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['addMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['rawImageMsg'] = _RAWIMAGEMSG
DESCRIPTOR.message_types_by_name['dotProductMsg'] = _DOTPRODUCTMSG
DESCRIPTOR.message_types_by_name['jsonImageMsg'] = _JSONIMAGEMSG
DESCRIPTOR.message_types_by_name['addReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['dotProductReply'] = _DOTPRODUCTREPLY
DESCRIPTOR.message_types_by_name['imageReply'] = _IMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.addMsg)
  })
_sym_db.RegisterMessage(addMsg)

rawImageMsg = _reflection.GeneratedProtocolMessageType('rawImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _RAWIMAGEMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.rawImageMsg)
  })
_sym_db.RegisterMessage(rawImageMsg)

dotProductMsg = _reflection.GeneratedProtocolMessageType('dotProductMsg', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.dotProductMsg)
  })
_sym_db.RegisterMessage(dotProductMsg)

jsonImageMsg = _reflection.GeneratedProtocolMessageType('jsonImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _JSONIMAGEMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.jsonImageMsg)
  })
_sym_db.RegisterMessage(jsonImageMsg)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.addReply)
  })
_sym_db.RegisterMessage(addReply)

dotProductReply = _reflection.GeneratedProtocolMessageType('dotProductReply', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.dotProductReply)
  })
_sym_db.RegisterMessage(dotProductReply)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.imageReply)
  })
_sym_db.RegisterMessage(imageReply)



_LAB6 = _descriptor.ServiceDescriptor(
  name='Lab6',
  full_name='lab6.Lab6',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoAdd',
    full_name='lab6.Lab6.DoAdd',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_ADDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DotProduct',
    full_name='lab6.Lab6.DotProduct',
    index=1,
    containing_service=None,
    input_type=_DOTPRODUCTMSG,
    output_type=_DOTPRODUCTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RawImage',
    full_name='lab6.Lab6.RawImage',
    index=2,
    containing_service=None,
    input_type=_RAWIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JsonImage',
    full_name='lab6.Lab6.JsonImage',
    index=3,
    containing_service=None,
    input_type=_JSONIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAB6)

DESCRIPTOR.services_by_name['Lab6'] = _LAB6

# @@protoc_insertion_point(module_scope)
